services:
  pocket-tts-wyoming:
    #image: ghcr.io/ikidd/pocket-tts-wyoming:latest
    build: .
    container_name: pocket-tts-wyoming
    network_mode: host
    environment:
      - WYOMING_PORT=10201
      - WYOMING_HOST=0.0.0.0
      - DEFAULT_VOICE=alba
      - MODEL_VARIANT=b6369a24
      - ZEROCONF=pocket-tts
    restart: unless-stopped
    volumes:
      - pocket-tts-hf-cache:/root/.cache/huggingface
      - pocket-tts-cache:/root/.cache/pocket_tts

volumes:
  pocket-tts-hf-cache:
    driver: local
  pocket-tts-cache:
    driver: local
