services:
  pocket-tts-wyoming:
    # image: ghcr.io/ikidd/pocket-tts-wyoming:latest
    build: .
    container_name: pocket-tts-wyoming
    network_mode: host
    environment:
      - WYOMING_PORT=10201
      - WYOMING_HOST=0.0.0.0
      - DEFAULT_VOICE=alba
      - ZEROCONF=pocket-tts
      - CUSTOM_VOICES_DIR=/custom_voices
    restart: unless-stopped
    volumes:
      - pocket-tts-hf-cache:/root/.cache/huggingface
      - pocket-tts-cache:/root/.cache/pocket_tts
      - ./custom_voices:/custom_voices
volumes:
  pocket-tts-hf-cache:
    driver: local
  pocket-tts-cache:
    driver: local
